export function generateRouteTree(): string {
  return `/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// This is a placeholder file that will be regenerated by the TanStack Router Vite plugin
// when you run 'npm run dev' or 'npm run build'

import { Route as rootRoute } from './routes/__root'

export interface FileRoutesByPath {}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByPath
  fullPaths: never
  fileRoutesByTo: FileRoutesByPath
  to: never
  id: '__root__'
  fileRoutesById: {
    __root__: typeof rootRoute
  }
}

export interface RootRouteChildren {}

const rootRouteChildren: RootRouteChildren = {}

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
`
}
