import type { MonorepoTemplateData } from "../../../../types";
import { PORT_API } from "../../constants";

export function generateServerIndex(data: MonorepoTemplateData): string {
  const { apiFramework } = data;

  if (apiFramework === "hono") {
    return generateHonoIndex(data);
  } else if (apiFramework === "express") {
    return generateExpressIndex(data);
  } else {
    return generateFastifyIndex(data);
  }
}

function generateHonoIndex(data: MonorepoTemplateData): string {
  const { scope, hasAuth } = data;

  const authImport = hasAuth ? `import { auth } from "${scope}/auth";\n` : "";
  const authRoute = hasAuth
    ? `\n// Auth routes (better-auth)\napp.on(["POST", "GET"], "/api/auth/**", (c) => auth.handler(c.req.raw));\n`
    : "";

  return `import { env } from "${scope}/env/server";
import { Hono } from "hono";
import { cors } from "hono/cors";
import { logger } from "hono/logger";
${authImport}
const app = new Hono();

app.use(logger());
app.use(
  "/*",
  cors({
    origin: env.CORS_ORIGIN,
    allowMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
    allowHeaders: ["Content-Type", "Authorization"],
    credentials: true,
  }),
);

app.get("/", (c) => c.text("OK"));
${authRoute}
// Example API resource (generated by honotan)
import { helloRoutes } from "./hello";
app.route("/api", helloRoutes);

export default app;
`;
}

function generateExpressIndex(data: MonorepoTemplateData): string {
  const { scope, hasAuth } = data;

  const authImport = hasAuth
    ? `import { toNodeHandler } from "better-auth/node";\nimport { auth } from "${scope}/auth";\n`
    : "";
  const authRoute = hasAuth
    ? `\n// Auth routes (better-auth)\napp.all("/api/auth/*", toNodeHandler(auth));\n`
    : "";

  return `import { env } from "${scope}/env/server";
import express from "express";
import cors from "cors";
${authImport}
const app = express();
const port = Number(env.PORT ?? ${PORT_API});

app.use(express.json());
app.use(cors({ origin: env.CORS_ORIGIN }));

app.get("/", (_req, res) => res.send("OK"));
${authRoute}
// Example API resource (generated by honotan)
import { helloRoutes } from "./hello";
app.use("/api", helloRoutes);

app.listen(port, () => {
  console.log(\`Server running on http://localhost:\${port}\`);
});
`;
}

function generateFastifyIndex(data: MonorepoTemplateData): string {
  const { scope, hasAuth } = data;

  const authImport = hasAuth
    ? `import { toNodeHandler } from "better-auth/node";\nimport { auth } from "${scope}/auth";\n`
    : "";
  const authRoute = hasAuth
    ? `\n// Auth routes (better-auth)\nfastify.all("/api/auth/*", async (request, reply) => {\n  const response = await toNodeHandler(auth)(request.raw, reply.raw);\n  return response;\n});\n`
    : "";

  return `import { env } from "${scope}/env/server";
import Fastify from "fastify";
${authImport}
const fastify = Fastify({ logger: true });
const port = Number(env.PORT ?? ${PORT_API});

fastify.get("/", async () => "OK");
${authRoute}
// Example API resource (generated by honotan)
import { helloPlugin } from "./hello";
fastify.register(helloPlugin, { prefix: "/api" });

fastify.listen({ port, host: "0.0.0.0" }, (err, address) => {
  if (err) { fastify.log.error(err); process.exit(1); }
  fastify.log.info(\`Server running on \${address}\`);
});
`;
}
