import type { ApiFramework } from '../../types';

export function generateStandaloneServerIndex(framework: ApiFramework): string {
  if (framework === 'hono') {
    return generateHonoIndex();
  } else if (framework === 'express') {
    return generateExpressIndex();
  } else {
    return generateFastifyIndex();
  }
}

function generateHonoIndex(): string {
  return `import { Hono } from "hono";
import { cors } from "hono/cors";
import { logger } from "hono/logger";
import { serve } from "@hono/node-server";

const port = Number(process.env.PORT ?? 3000);
const app = new Hono();

app.use(logger());
app.use("/*", cors());

app.get("/", (c) => c.text("OK"));

// Example API resource (generated by honotan)
import { helloRoutes } from "./hello";
app.route("/api", helloRoutes);

serve({ fetch: app.fetch, port }, (info) => {
  console.log(\`Server running on http://localhost:\${info.port}\`);
});
`;
}

function generateExpressIndex(): string {
  return `import express from "express";
import cors from "cors";

const app = express();
const port = Number(process.env.PORT ?? 3000);

app.use(express.json());
app.use(cors());

app.get("/", (_req, res) => res.send("OK"));

// Example API resource (generated by honotan)
import { helloRoutes } from "./hello";
app.use("/api", helloRoutes);

app.listen(port, () => {
  console.log(\`Server running on http://localhost:\${port}\`);
});
`;
}

function generateFastifyIndex(): string {
  return `import Fastify from "fastify";

const fastify = Fastify({ logger: true });
const port = Number(process.env.PORT ?? 3000);

fastify.get("/", async () => "OK");

// Example API resource (generated by honotan)
import { helloPlugin } from "./hello";
fastify.register(helloPlugin, { prefix: "/api" });

fastify.listen({ port, host: "0.0.0.0" }, (err, address) => {
  if (err) { fastify.log.error(err); process.exit(1); }
  fastify.log.info(\`Server running on \${address}\`);
});
`;
}
